#!/bin/sh

# focus next and prev window
riverctl map normal Alt j focus-view next
riverctl map normal Alt k focus-view previous

# focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# bump the focused view to the top of the layout stack
riverctl map normal Super g zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control h send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control l send-layout-cmd rivertile "main-ratio +0.05"

# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# move floating window
riverctl map normal Alt+Shift L move right 100
riverctl map normal Alt+Shift H move left 100
riverctl map normal Alt+Shift K move up 100
riverctl map normal Alt+Shift J move down 100

# snap floating window to screen edges
#riverctl map normal Alt+Control H snap left
#riverctl map normal Alt+Control J snap down
#riverctl map normal Alt+Control K snap up
#riverctl map normal Alt+Control L snap right

# resize floating window
#riverctl map normal Super+Control h resize horizontal -100
#riverctl map normal Super+Control j resize vertical 100
#riverctl map normal Super+Control k resize vertical -100
#riverctl map normal Super+Control l resize horizontal 100

# move window with mouse
riverctl map-pointer normal Super BTN_LEFT move-view

# resize window with mouse
riverctl map-pointer normal Super BTN_RIGHT resize-view

# toggle floating window with mouse
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Alt $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Alt+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Alt+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Alt+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Alt F12 toggle-float

# Super+F to toggle fullscreen
riverctl map normal Alt F11 toggle-fullscreen

# Set background and border color
#riverctl background-color 0x002b36
#riverctl border-color-focused 0x93a1a1
#riverctl border-color-unfocused 0x586e75
riverctl border-width 1

# Set keyboard repeat rate
riverctl set-repeat 30 200

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

# keyboard
riverctl keyboard-layout -variant ",qwerty" -options "grp_led:scroll,grp:win_space_toggle,caps:swapescape,keypad:pointerkeys" "us,ara"

# mouse
riverctl hide-cursor when-typing enabled

riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad events disabled-on-external-mouse
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad click-method clickfinger
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad drag enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad disable-while-typing enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap-button-map left-right-middle
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad scroll-method two-finger
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled
riverctl hide-cursor timeout 3000
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad events enabled

# profile
[ -x $HOME/.config/river/map ] && . $HOME/.config/river/map &
[ -x $HOME/.config/river/autostart ] && . $HOME/.config/river/autostart &
