#!/usr/bin/sh

sh $HOME/.fehbg

pidof xbanish || xbanish 2> /dev/null &

#pidof picom || picom 2> /dev/null &

pidof polybar || polybar bar1 2> /dev/null &

pidof keynav || keynav daemonize 2> /dev/null &

exec prime-run alacritty

